# Base configs
baseurl: "http://hazelday.com"
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photos of Hazel Day Catron"
subtitle: ""
author: "Wade Catron"
header:
 title: "Hazel Hazel"
 subtitle: "by Wade Catron"
footer:
 name: "Hi, enjoy some pictures of Hazel."
 bio: "They are pretty cool."
 github: "Also visit the <a href=\"https://photos.google.com/share/AF1QipPAOkYNtMFfdDuziDsHhnECbSz0dgxFv5mKu9x3hgcpppMdo556DWu3zS0oqd7nnQ?key=elQxOGgyN1k5d1BFUEQ4V1dOa3A0dUlxMlJrODZR\">Google Photos shared album</a>!"
web_design: "AJ"
